# Generated by Django 5.2.17 on 2026-08-29 08:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_intelligence", "0007_aialert_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        default="disabled",
                        max_length=16,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("staff", "Staff only"),
                            ("users", "Authenticated users"),
                            ("public", "Public"),
                        ],
                        default="staff",
                        max_length=16,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("viewer", "Read-only"),
                            ("operator", "Operator (can execute state-changing tools)"),
                            ("admin", "Admin (higher-risk tools allowed)"),
                        ],
                        default="operator",
                        help_text="Agent-level capability ceiling; per-tool server-side permissions still apply.",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "prompt_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Active-prompt key from the Phase 18.2 prompt registry.",
                        max_length=100,
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=100)),
                ("model_name", models.CharField(blank=True, default="", max_length=200)),
                ("system_instructions", models.TextField(blank=True, default="")),
                ("enabled_tools", models.JSONField(blank=True, default=list)),
                ("max_turns", models.PositiveIntegerField(blank=True, null=True)),
                ("max_tool_calls", models.PositiveIntegerField(blank=True, null=True)),
                ("max_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "max_cost_usd",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                ("timeout_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked AI feature (feature-flag gating + telemetry).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents",
                        to="ai_intelligence.aifeatureregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AgentConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("paused", "Paused"), ("closed", "Closed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="agents.agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent conversation",
                "verbose_name_plural": "Agent conversations",
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("run_key", models.UUIDField(db_index=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated (guardrail)"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("termination_reason", models.CharField(blank=True, default="", max_length=100)),
                ("provider", models.CharField(blank=True, default="", max_length=100)),
                ("model_name", models.CharField(blank=True, default="", max_length=200)),
                ("prompt_key", models.CharField(blank=True, default="", max_length=100)),
                ("prompt_version", models.PositiveIntegerField(default=0)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=10),
                ),
                ("turn_count", models.PositiveIntegerField(default=0)),
                ("tool_call_count", models.PositiveIntegerField(default=0)),
                ("consecutive_tool_failures", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="agents.agent",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="agents.agentconversation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=100)),
                ("arguments", models.JSONField(blank=True, default=dict)),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("executed", "Executed"),
                            ("proposed", "Proposed for review"),
                            ("denied", "Denied"),
                            ("failed", "Failed"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                (
                    "permission_decision",
                    models.CharField(
                        choices=[
                            ("read_allowed", "Read allowed — executed"),
                            ("proposed", "State-changing — proposal created"),
                            ("denied", "Denied"),
                        ],
                        default="denied",
                        max_length=16,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="agents.agentrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent tool call",
                "ordering": ["started_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("proposal_key", models.UUIDField(db_index=True, unique=True)),
                ("proposal_type", models.CharField(blank=True, default="", max_length=64)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("summary", models.TextField(blank=True, default="")),
                ("action", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("applied", "Applied"),
                            ("failed", "Apply failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "approval_required",
                    models.CharField(
                        choices=[("any_staff", "Any staff member"), ("admin", "Admin only")],
                        default="any_staff",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("application_result", models.JSONField(blank=True, default=dict)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="agents.agentrun",
                    ),
                ),
                (
                    "tool_call",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposal",
                        to="agents.agenttoolcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent proposal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("tool", "Tool"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agents.agentconversation",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="agents.agentrun",
                    ),
                ),
                (
                    "tool_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="agents.agenttoolcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent message",
                "ordering": ["sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["status", "created_at"], name="agents_agen_status_27cafa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["conversation", "created_at"], name="agents_agen_convers_61d87d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agenttoolcall",
            index=models.Index(fields=["run", "tool_name"], name="agents_agen_run_id_52b520_idx"),
        ),
        migrations.AddIndex(
            model_name="agenttoolcall",
            index=models.Index(
                fields=["tool_name", "created_at"], name="agents_agen_tool_na_c3b7cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentproposal",
            index=models.Index(
                fields=["status", "created_at"], name="agents_agen_status_0cb0f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentproposal",
            index=models.Index(fields=["expires_at"], name="agents_agen_expires_da6fa9_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentmessage",
            constraint=models.UniqueConstraint(
                fields=("conversation", "sequence"), name="uniq_message_sequence_per_conversation"
            ),
        ),
    ]
