# Generated by Django 5.2.17 on 2026-08-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_review_photos_review_replied_at_review_reply"),
        ("brokers", "0001_initial"),
        ("corporate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="broker_referral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="brokers.brokerprofile",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="corporate_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="corporate.corporateaccount",
            ),
        ),
    ]
