# Generated by Django 5.2.17 on 2026-08-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_booking_broker_referral_booking_corporate_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending", "Pending Moderation"),
                    ("rejected", "Rejected"),
                    ("escalated", "Escalated"),
                ],
                default="approved",
                help_text="Moderation queue status. Default 'approved' preserves existing behaviour.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="trust_score",
            field=models.IntegerField(
                blank=True,
                help_text="Computed trust score 0-100. Null until scored by the review-trust detector.",
                null=True,
            ),
        ),
    ]
