# Generated by Django 5.2.16 on 2026-07-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_request', 'Booking Request'), ('booking_approved', 'Booking Approved'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('new_review', 'New Review'), ('new_message', 'New Message'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('system', 'System')], max_length=20),
        ),
    ]
