# Generated by Django 5.2.16 on 2026-08-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_alter_notification_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("template_name", models.CharField(max_length=100)),
                ("subject", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped (rate limit / backoff)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "template_name", "created_at"],
                        name="notificatio_recipie_5c4ed4_idx",
                    )
                ],
            },
        ),
    ]
