# Generated by Django 5.2.16 on 2026-08-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0008_notification_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_request", "Booking Request"),
                    ("booking_approved", "Booking Approved"),
                    ("booking_rejected", "Booking Rejected"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("new_review", "New Review"),
                    ("new_message", "New Message"),
                    ("payment_success", "Payment Success"),
                    ("payment_failed", "Payment Failed"),
                    ("payment_reminder", "Payment Reminder"),
                    ("roommate_request", "Roommate Request"),
                    ("roommate_approved", "Roommate Approved"),
                    ("fraud_flag", "Fraud Flag"),
                    ("kyc_sla_breach", "KYC SLA Breach"),
                    ("tenant_kyc_approved", "Tenant KYC Approved"),
                    ("tenant_kyc_rejected", "Tenant KYC Rejected"),
                    ("tenant_kyc_needs_review", "Tenant KYC Needs Review"),
                    ("saved_search_match", "Saved Search Match"),
                    ("system", "System"),
                ],
                max_length=32,
            ),
        ),
    ]
