# Generated by Django 5.2.17 on 2026-08-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0012_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_request", "Booking Request"),
                    ("booking_approved", "Booking Approved"),
                    ("booking_rejected", "Booking Rejected"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("new_review", "New Review"),
                    ("new_message", "New Message"),
                    ("payment_success", "Payment Success"),
                    ("payment_failed", "Payment Failed"),
                    ("payment_reminder", "Payment Reminder"),
                    ("roommate_request", "Roommate Request"),
                    ("roommate_approved", "Roommate Approved"),
                    ("fraud_flag", "Fraud Flag"),
                    ("kyc_sla_breach", "KYC SLA Breach"),
                    ("tenant_kyc_approved", "Tenant KYC Approved"),
                    ("tenant_kyc_rejected", "Tenant KYC Rejected"),
                    ("tenant_kyc_needs_review", "Tenant KYC Needs Review"),
                    ("account_warning", "Account Warning"),
                    ("account_suspended", "Account Suspended"),
                    ("report_resolved", "Report Resolved"),
                    ("content_moderated", "Content Moderated"),
                    ("dispute_opened", "Dispute Opened"),
                    ("dispute_update", "Dispute Update"),
                    ("saved_search_match", "Saved Search Match"),
                    ("system", "System"),
                    ("subscription_active", "Subscription Active"),
                    ("subscription_canceled", "Subscription Canceled"),
                    ("subscription_expired", "Subscription Expired"),
                    ("subscription_renewal_reminder", "Subscription Renewal Reminder"),
                    ("payout_requested", "Payout Requested"),
                    ("payout_approved", "Payout Approved"),
                    ("payout_paid", "Payout Paid"),
                    ("payout_rejected", "Payout Rejected"),
                    ("commission_earned", "Commission Earned"),
                    ("broker_submitted", "Broker Submitted"),
                    ("broker_verified", "Broker Verified"),
                    ("broker_rejected", "Broker Rejected"),
                    ("corporate_account_created", "Corporate Account Created"),
                    ("corporate_invoice", "Corporate Invoice"),
                    ("addon_provider_submitted", "Add-on Provider Submitted"),
                    ("addon_order_confirmed", "Add-on Order Confirmed"),
                    ("insurance_policy_issued", "Insurance Policy Issued"),
                ],
                max_length=32,
            ),
        ),
    ]
