# Generated by Django 5.2.16 on 2026-08-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="tier",
            field=models.CharField(
                choices=[("free", "Free"), ("featured", "Featured"), ("premium", "Premium")],
                default="free",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="tier_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
