# Generated by Django 5.2.16 on 2026-08-08 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_room_tier_room_tier_expires_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["lat", "lng"], name="room_lat_lng_idx"),
        ),
    ]
