# Generated by Django 5.2.16 on 2026-08-19 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0006_roompricehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomVisionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(default="heuristic", max_length=16)),
                ("caption", models.TextField(blank=True, default="")),
                ("observations", models.JSONField(default=list)),
                ("suggested_amenities", models.JSONField(default=list)),
                ("palette", models.JSONField(default=list)),
                ("photo_profiles", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vision_analysis",
                        to="rooms.room",
                    ),
                ),
            ],
        ),
    ]
