# Generated by Django 5.2.17 on 2026-08-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0007_roomvisionanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomimage",
            name="photo_gps_accuracy",
            field=models.CharField(
                blank=True,
                default="",
                help_text="GPS accuracy: high (with GPS method), medium (GPS data present), or empty.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="roomimage",
            name="photo_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude extracted from photo EXIF data.",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roomimage",
            name="photo_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude extracted from photo EXIF data.",
                max_digits=9,
                null=True,
            ),
        ),
    ]
