# Generated by Django 5.2.16 on 2026-08-13 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSafetyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("warned", "Warned"),
                            ("flagged", "Flagged"),
                            ("blocked", "Blocked"),
                        ],
                        max_length=10,
                    ),
                ),
                ("detectors", models.JSONField(blank=True, default=list)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_events",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_event",
                        to="chat.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_safety_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "created_at"], name="chat_chatsa_sender__ea2766_idx"
                    ),
                    models.Index(
                        fields=["chat_room", "created_at"], name="chat_chatsa_chat_ro_a807ae_idx"
                    ),
                    models.Index(
                        fields=["outcome", "created_at"], name="chat_chatsa_outcome_50ad90_idx"
                    ),
                ],
            },
        ),
    ]
