# Generated by Django 5.2.16 on 2026-08-13 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatsafetyevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("scam", "Scam"),
                            ("harassment", "Harassment"),
                            ("fake_listing", "Fake listing"),
                            ("payment_fraud", "Payment fraud"),
                            ("impersonation", "Impersonation"),
                            ("spam", "Spam"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                            ("escalated", "Escalated"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("", "—"),
                            ("warn", "Warned"),
                            ("suspend", "Suspended"),
                            ("escalate", "Escalated"),
                            ("dismiss", "Dismissed"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific message being reported (e.g. a suspicious payment request).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="chat.message",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="chat_report_status_32cad0_idx"
                    ),
                    models.Index(
                        fields=["target_user", "created_at"], name="chat_report_target__c0cbd7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("blocker", "blocked")},
            },
        ),
    ]
