# Generated by Django 5.2.16 on 2026-08-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savedsearches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="digest_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
