# Generated by Django 5.2.16 on 2026-08-16 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event", models.CharField(db_index=True, max_length=64)),
                ("category", models.CharField(blank=True, default="", max_length=32)),
                ("properties", models.JSONField(blank=True, default=dict)),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("path", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "created_at"], name="analytics_e_event_cfe9f0_idx"
                    ),
                    models.Index(fields=["created_at"], name="analytics_e_created_7b5fb3_idx"),
                ],
            },
        ),
    ]
