# Generated by Django 5.2.16 on 2026-08-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaPriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("area", models.CharField(max_length=50)),
                ("room_type", models.CharField(max_length=10)),
                ("week_start", models.DateField(db_index=True)),
                ("avg_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("median_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sample_size", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["week_start", "area", "room_type"],
                "unique_together": {("area", "room_type", "week_start")},
            },
        ),
    ]
