# Generated by Django 5.2.17 on 2026-08-24 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFeatureRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "feature_id",
                    models.CharField(
                        help_text="Unique feature identifier (e.g. liveness_detection, face_match).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human-readable feature name.", max_length=200),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fraud", "Fraud Detection"),
                            ("kyc", "Identity Verification"),
                            ("search", "Search & Discovery"),
                            ("recommendations", "Recommendations"),
                            ("pricing", "Pricing"),
                            ("chat", "Chat & Communication"),
                            ("copilot", "AI Copilot"),
                            ("embeddings", "Embeddings"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, help_text="Master switch for this feature."),
                ),
                (
                    "default_provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Default provider name for this feature.",
                        max_length=100,
                    ),
                ),
                (
                    "available_providers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of registered provider names (e.g. ["rules", "http"]).',
                    ),
                ),
                (
                    "settings_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Django setting name that selects the active provider.",
                        max_length=200,
                    ),
                ),
                (
                    "estimated_cost_per_request",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Estimated cost per request in USD (0 if free).",
                        max_digits=10,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional feature configuration (provider-specific).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Feature",
                "verbose_name_plural": "AI Features",
                "ordering": ["feature_id"],
            },
        ),
        migrations.CreateModel(
            name="ProviderHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=100)),
                ("feature_key", models.CharField(db_index=True, max_length=100)),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("successful_requests", models.PositiveIntegerField(default=0)),
                ("failed_requests", models.PositiveIntegerField(default=0)),
                ("timeout_requests", models.PositiveIntegerField(default=0)),
                ("avg_latency_ms", models.PositiveIntegerField(default=0)),
                ("p95_latency_ms", models.PositiveIntegerField(default=0)),
                ("p99_latency_ms", models.PositiveIntegerField(default=0)),
                ("total_cost_usd", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("total_input_tokens", models.PositiveIntegerField(default=0)),
                ("total_output_tokens", models.PositiveIntegerField(default=0)),
                ("success_rate", models.FloatField(default=0, help_text="Success rate (0.0-1.0).")),
                (
                    "is_healthy",
                    models.BooleanField(
                        default=True, help_text="False if success_rate drops below threshold."
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-window_start"],
                "indexes": [
                    models.Index(
                        fields=["provider", "feature_key", "window_start"],
                        name="provider_health_lookup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "feature_key", "window_start"),
                        name="provider_health_window_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "execution_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique execution ID for request correlation.",
                    ),
                ),
                (
                    "feature_key",
                    models.CharField(
                        db_index=True,
                        help_text="Feature identifier (denormalized for fast queries).",
                        max_length=100,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Provider name that handled this request.", max_length=100
                    ),
                ),
                (
                    "provider_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider version if available.",
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AI model name if applicable (e.g. gpt-4, sentence-transformers).",
                        max_length=200,
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AI model version if applicable.",
                        max_length=100,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HTTP request ID for correlation (from RequestCorrelationMiddleware).",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("fallback", "Fallback"),
                            ("timeout", "Timeout"),
                            ("rate_limited", "Rate Limited"),
                        ],
                        db_index=True,
                        default="success",
                        max_length=16,
                    ),
                ),
                (
                    "failure_type",
                    models.CharField(
                        choices=[
                            ("user_failure", "User Failure"),
                            ("provider_failure", "Provider Failure"),
                            ("system_failure", "System Failure"),
                            ("none", "No Failure"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Sanitized error message (no secrets/PII).",
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="Provider execution latency in milliseconds."
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="Input tokens consumed (0 if not applicable)."
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="Output tokens produced (0 if not applicable)."
                    ),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="Total tokens (input + output, 0 if not applicable)."
                    ),
                ),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Estimated cost in USD (0 if free or unknown).",
                        max_digits=10,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0,
                        help_text="Provider confidence score (0.0-1.0, 0 if not applicable).",
                    ),
                ),
                (
                    "is_fallback",
                    models.BooleanField(
                        default=False,
                        help_text="True if this was a fallback attempt after primary failure.",
                    ),
                ),
                (
                    "fallback_chain",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of providers tried before success (e.g. ["http", "rules"]).',
                    ),
                ),
                (
                    "primary_provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The primary provider that failed (if fallback was used).",
                        max_length=100,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional provider-specific telemetry (e.g. raw scores, flags).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_execution_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_logs",
                        to="ai_intelligence.aifeatureregistry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["feature_key", "created_at"], name="ai_exec_feature_time_idx"
                    ),
                    models.Index(
                        fields=["provider", "status", "created_at"],
                        name="ai_exec_provider_status_idx",
                    ),
                    models.Index(fields=["user", "created_at"], name="ai_exec_user_time_idx"),
                    models.Index(fields=["execution_id"], name="ai_exec_id_idx"),
                ],
            },
        ),
    ]
