# Generated by Django 5.2.17 on 2026-08-24 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_intelligence", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiexecutionlog",
            name="execution_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique execution ID for request correlation.",
                unique=True,
            ),
        ),
    ]
