# Generated by Django 5.2.17 on 2026-08-24 04:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_intelligence", "0002_add_execution_id_unique"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="aiexecutionlog",
            name="ai_exec_id_idx",
        ),
    ]
