# Generated by Django 5.2.17 on 2026-08-25 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_intelligence", "0003_remove_aiexecutionlog_ai_exec_id_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiexecutionlog",
            name="prompt_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Prompt registry key if applicable.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="aiexecutionlog",
            name="prompt_version",
            field=models.PositiveIntegerField(
                default=0, help_text="Prompt version number (0 if not applicable)."
            ),
        ),
        migrations.AddField(
            model_name="aifeatureregistry",
            name="default_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Default model name (e.g. gpt-4o, sentence-transformers).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="aifeatureregistry",
            name="fallback_strategy",
            field=models.CharField(
                choices=[
                    ("none", "No fallback"),
                    ("rules", "Fall back to rules engine"),
                    ("cache", "Fall back to cached result"),
                    ("degraded", "Serve degraded response"),
                ],
                default="none",
                help_text="Fallback behavior when primary provider fails.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="aifeatureregistry",
            name="feature_flag_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional linked feature flag key for gating.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="aifeatureregistry",
            name="owner",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Team or person responsible for this feature.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="aifeatureregistry",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("beta", "Beta"),
                    ("deprecated", "Deprecated"),
                    ("disabled", "Disabled"),
                ],
                default="active",
                help_text="Feature lifecycle status.",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="AIPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "prompt_key",
                    models.CharField(
                        db_index=True,
                        help_text="Stable identifier (e.g. ai.copilot.search).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Human-readable prompt name.", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fraud", "Fraud Detection"),
                            ("kyc", "Identity Verification"),
                            ("search", "Search & Discovery"),
                            ("recommendations", "Recommendations"),
                            ("pricing", "Pricing"),
                            ("chat", "Chat & Communication"),
                            ("copilot", "AI Copilot"),
                            ("embeddings", "Embeddings"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("template", "LLM Prompt Template"),
                            ("rules", "Deterministic Rules"),
                            ("config", "Configuration"),
                        ],
                        default="template",
                        max_length=16,
                    ),
                ),
                (
                    "default_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Required model/capability (e.g. gpt-4o, sentence-transformers).",
                        max_length=200,
                    ),
                ),
                (
                    "input_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Expected input variables and their types.",
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        blank=True, default=dict, help_text="Expected output format description."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("draft", "Draft"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompts",
                        to="ai_intelligence.aifeatureregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Prompt",
                "verbose_name_plural": "AI Prompts",
                "ordering": ["prompt_key"],
            },
        ),
        migrations.CreateModel(
            name="AIPromptVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        help_text="Version number (auto-incrementing per prompt)."
                    ),
                ),
                (
                    "template",
                    models.TextField(help_text="The prompt template, rule set, or configuration."),
                ),
                (
                    "system_instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="System-level instructions (for LLM templates).",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Variable definitions with types, defaults, and descriptions.",
                    ),
                ),
                (
                    "model_requirement",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Required model or capability for this version.",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="inactive",
                        max_length=16,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Only one version per prompt can be active."
                    ),
                ),
                (
                    "change_summary",
                    models.TextField(
                        blank=True, default="", help_text="Why this version was created."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_prompt_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="ai_intelligence.aiprompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Prompt Version",
                "verbose_name_plural": "AI Prompt Versions",
                "ordering": ["prompt", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prompt", "version"), name="ai_prompt_version_unique"
                    )
                ],
            },
        ),
    ]
