# Generated by Django 5.2.17 on 2026-08-26 04:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_intelligence", "0004_aiexecutionlog_prompt_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric_key",
                    models.CharField(
                        db_index=True,
                        help_text="Stable identifier (e.g. f1, ndcg, precision_at_k).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("deterministic", "Deterministic"),
                            ("heuristic", "Heuristic"),
                            ("llm_judge", "LLM-as-Judge"),
                            ("human", "Human Evaluation"),
                        ],
                        default="deterministic",
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("search", "Search"),
                            ("recommendation", "Recommendation"),
                            ("classification", "Classification"),
                            ("fraud", "Fraud Detection"),
                            ("prediction", "Prediction"),
                            ("llm", "LLM Quality"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                (
                    "formula",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of how this metric is computed.",
                    ),
                ),
                (
                    "is_higher_better",
                    models.BooleanField(
                        default=True,
                        help_text="True if higher values are better (False for MAE, RMSE, etc.).",
                    ),
                ),
                (
                    "default_threshold",
                    models.FloatField(
                        blank=True,
                        help_text="Default quality threshold for this metric (nullable).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["metric_key"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dataset_key",
                    models.CharField(
                        db_index=True,
                        help_text="Stable identifier (e.g. search.uttara.relevance).",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[
                            ("synthetic", "Synthetic"),
                            ("anonymized", "Anonymized"),
                            ("manual_review", "Manually Reviewed"),
                            ("approved", "Approved"),
                        ],
                        default="synthetic",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In Review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number (immutable once published)."
                    ),
                ),
                (
                    "sample_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of evaluation cases (denormalized)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_datasets",
                        to="ai_intelligence.aifeatureregistry",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset_key", "-version"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "case_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional stable ID within the dataset (e.g. 'case_001').",
                        max_length=100,
                    ),
                ),
                ("input", models.JSONField(help_text="Test input data.")),
                (
                    "expected_output",
                    models.JSONField(
                        blank=True,
                        help_text="Expected/reference output (nullable for open-ended tasks).",
                        null=True,
                    ),
                ),
                (
                    "expected_labels",
                    models.JSONField(
                        blank=True,
                        help_text="Expected labels for classification (e.g. ['fraud', 'high_risk']).",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Category, difficulty, tags, etc."
                    ),
                ),
                (
                    "evaluation_criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="What to measure for this case (metric overrides, thresholds).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="ai_intelligence.evaluationdataset",
                    ),
                ),
            ],
            options={
                "ordering": ["dataset", "id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "run_key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique run ID for correlation.",
                        unique=True,
                    ),
                ),
                (
                    "dataset_version",
                    models.PositiveIntegerField(
                        default=0, help_text="Snapshot of dataset version at run time."
                    ),
                ),
                (
                    "prompt_version",
                    models.PositiveIntegerField(
                        default=0, help_text="Snapshot of prompt version at run time."
                    ),
                ),
                ("model_name", models.CharField(blank=True, default="", max_length=200)),
                ("provider", models.CharField(blank=True, default="", max_length=100)),
                (
                    "experiment_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Experiment key for A/B comparison (nullable).",
                        max_length=128,
                    ),
                ),
                (
                    "variant_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Experiment variant key (nullable).",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="Total execution time in milliseconds."
                    ),
                ),
                ("total_cases", models.PositiveIntegerField(default=0)),
                ("passed_cases", models.PositiveIntegerField(default=0)),
                ("failed_cases", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "score",
                    models.FloatField(
                        default=0,
                        help_text="Composite score (0.0-1.0, weighted average of metrics).",
                    ),
                ),
                (
                    "metric_scores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Per-metric scores (e.g. {"f1": 0.91, "precision": 0.88}).',
                    ),
                ),
                ("total_cost_usd", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                (
                    "max_cases",
                    models.PositiveIntegerField(
                        default=1000, help_text="Maximum cases to evaluate (cost safeguard)."
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=3600, help_text="Maximum execution time in seconds."
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "baseline_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Baseline run for comparison (nullable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comparison_runs",
                        to="ai_intelligence.evaluationrun",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_runs",
                        to="ai_intelligence.evaluationdataset",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_runs",
                        to="ai_intelligence.aifeatureregistry",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_runs",
                        to="ai_intelligence.aiprompt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationCaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(help_text="Snapshot of the input at evaluation time."),
                ),
                (
                    "actual_output",
                    models.JSONField(blank=True, help_text="AI output for this case.", null=True),
                ),
                (
                    "expected_output",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of expected output at evaluation time.",
                        null=True,
                    ),
                ),
                (
                    "metric_results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Per-metric scores (e.g. {"f1": 0.95, "precision": 0.92}).',
                    ),
                ),
                ("passed", models.BooleanField(db_index=True, default=False)),
                ("score", models.FloatField(default=0, help_text="Composite score for this case.")),
                (
                    "confidence",
                    models.FloatField(
                        default=0, help_text="Model confidence for this case (0.0-1.0)."
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", help_text="Sanitized error message if case failed."
                    ),
                ),
                (
                    "evaluator_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Version of the evaluator used.",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="ai_intelligence.evaluationcase",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_results",
                        to="ai_intelligence.evaluationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "threshold_min",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum acceptable value (nullable = no min).",
                        null=True,
                    ),
                ),
                (
                    "threshold_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum acceptable value (nullable = no max).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_thresholds",
                        to="ai_intelligence.aifeatureregistry",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thresholds",
                        to="ai_intelligence.evaluationmetric",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="evaluationdataset",
            constraint=models.UniqueConstraint(
                fields=("dataset_key", "version"), name="eval_dataset_version_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationcase",
            index=models.Index(fields=["dataset", "created_at"], name="eval_case_dataset_idx"),
        ),
        migrations.AddIndex(
            model_name="evaluationrun",
            index=models.Index(fields=["feature", "created_at"], name="eval_run_feature_time_idx"),
        ),
        migrations.AddIndex(
            model_name="evaluationrun",
            index=models.Index(fields=["status", "created_at"], name="eval_run_status_time_idx"),
        ),
        migrations.AddIndex(
            model_name="evaluationcaseresult",
            index=models.Index(fields=["run", "passed"], name="eval_caseresult_run_pass_idx"),
        ),
        migrations.AddIndex(
            model_name="evaluationcaseresult",
            index=models.Index(fields=["run", "score"], name="eval_caseresult_run_score_idx"),
        ),
        migrations.AddConstraint(
            model_name="evaluationthreshold",
            constraint=models.UniqueConstraint(
                fields=("feature", "metric"), name="eval_threshold_feature_metric_unique"
            ),
        ),
    ]
