# Generated by Django 5.2.17 on 2026-08-29 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_intelligence", "0005_evaluationmetric_evaluationdataset_evaluationcase_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rule_key",
                    models.CharField(
                        help_text="Unique rule identifier (e.g. copilot_error_rate).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("reliability", "Reliability"),
                            ("performance", "Performance"),
                            ("quality", "Quality"),
                            ("cost", "Cost"),
                            ("drift", "Drift"),
                            ("availability", "Availability"),
                        ],
                        default="reliability",
                        max_length=30,
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("error_rate", "Error rate"),
                            ("timeout_rate", "Timeout rate"),
                            ("fallback_rate", "Fallback rate"),
                            ("success_rate", "Success rate"),
                            ("avg_latency", "Average latency (ms)"),
                            ("p95_latency", "P95 latency (ms)"),
                            ("daily_cost", "Daily estimated cost (USD)"),
                            ("cost_per_execution", "Cost per execution (USD)"),
                            ("evaluation_score", "Evaluation score"),
                            ("drift_breach", "Model drift breach"),
                        ],
                        help_text="The metric this rule watches.",
                        max_length=40,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[("gt", ">"), ("gte", ">="), ("lt", "<"), ("lte", "<=")],
                        default="gt",
                        max_length=10,
                    ),
                ),
                (
                    "threshold_value",
                    models.FloatField(help_text="Threshold the metric is compared against."),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=100)),
                ("model_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Look-back window (minutes) used to compute the metric.",
                    ),
                ),
                (
                    "consecutive_checks",
                    models.PositiveIntegerField(
                        default=1, help_text="Trigger only after this many consecutive breaches."
                    ),
                ),
                (
                    "cooldown_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Minimum minutes between alerts for the same scope."
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "notify_admins",
                    models.BooleanField(
                        default=True,
                        help_text="Create in-app Notification(s) for staff/admins when it fires.",
                    ),
                ),
                ("breach_count", models.PositiveIntegerField(default=0)),
                ("last_metric_value", models.FloatField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ai_alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="ai_intelligence.aifeatureregistry",
                    ),
                ),
            ],
            options={
                "ordering": ["rule_key"],
            },
        ),
        migrations.CreateModel(
            name="AIAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("alert_key", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("reliability", "Reliability"),
                            ("performance", "Performance"),
                            ("quality", "Quality"),
                            ("cost", "Cost"),
                            ("drift", "Drift"),
                            ("availability", "Availability"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("triggered", "Triggered"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("suppressed", "Suppressed"),
                        ],
                        db_index=True,
                        default="triggered",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("metric_name", models.CharField(max_length=40)),
                ("metric_value", models.FloatField(default=0.0)),
                ("threshold_value", models.FloatField(default=0.0)),
                ("provider", models.CharField(blank=True, default="", max_length=100)),
                ("model_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "dedup_key",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("breach_count", models.PositiveIntegerField(default=1)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, default="")),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_ai_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_alerts",
                        to="ai_intelligence.aifeatureregistry",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_ai_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="ai_intelligence.aialertrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
                "indexes": [
                    models.Index(
                        fields=["alert_type", "triggered_at"], name="ai_alert_type_time_idx"
                    ),
                    models.Index(
                        fields=["status", "triggered_at"], name="ai_alert_status_time_idx"
                    ),
                    models.Index(fields=["severity", "status"], name="ai_alert_sev_status_idx"),
                ],
            },
        ),
    ]
