# Generated by Django 5.2.17 on 2026-08-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_intelligence", "0006_aialertrule_aialert"),
    ]

    operations = [
        migrations.AddField(
            model_name="aialert",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
