# Generated by Django 5.2.17 on 2026-08-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fraud", "0004_alter_fraudsignal_detector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fraudsignal",
            name="detector",
            field=models.CharField(
                choices=[
                    ("duplicate_listing", "Duplicate Listing"),
                    ("suspicious_price", "Suspicious Price"),
                    ("missing_images", "Missing Images"),
                    ("rapid_listing", "Rapid Listing"),
                    ("unverified_owner", "Unverified Owner"),
                    ("description_similarity", "Description Similarity"),
                    ("duplicate_image", "Duplicate Image"),
                    ("manipulated_image", "Manipulated Image"),
                    ("fraud_ring", "Fraud Ring"),
                    ("photo_geo_mismatch", "Photo-Geo Mismatch"),
                    ("liveness_failed", "Liveness Check Failed"),
                    ("face_match_failed", "Face Match Failed"),
                    ("review_fake", "Fake Review Detected"),
                    ("review_spam", "Review Spam Detected"),
                    ("kyc_liveness_missing", "KYC Liveness Not Completed"),
                ],
                max_length=30,
            ),
        ),
    ]
