# Generated by Django 5.2.17 on 2026-08-22 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fraud", "0005_alter_fraudsignal_detector"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("room", "Room"),
                            ("device", "Device"),
                            ("payment", "Payment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("entity_id", models.CharField(max_length=100)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable label (username, room title, etc.).",
                        max_length=255,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "risk_score",
                    models.IntegerField(
                        default=0,
                        help_text="0-100 risk score computed from connected edges and neighbours.",
                    ),
                ),
                (
                    "community_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Community cluster id assigned by the last graph rebuild.",
                        null=True,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-risk_score", "-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="fraud_graph_entity__4a1451_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "risk_score"], name="fraud_graph_entity__70a991_idx"
                    ),
                    models.Index(fields=["community_id"], name="fraud_graph_communi_5dd576_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity_type", "entity_id"), name="uq_graph_node_entity"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GraphEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("phone", "Shared Phone"),
                            ("ip", "Shared IP"),
                            ("device", "Shared Device"),
                            ("nid", "Shared NID"),
                            ("payment", "Shared Payment"),
                            ("behavioral", "Behavioral Similarity"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        choices=[
                            ("strong", "Strong"),
                            ("weak", "Weak"),
                            ("potential", "Potential"),
                        ],
                        default="weak",
                        max_length=10,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=0.5,
                        help_text="0.0-1.0 weight used for community detection and risk propagation.",
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Supporting data: phone number, IP address, device id, etc.",
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="fraud.graphnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="fraud.graphnode",
                    ),
                ),
            ],
            options={
                "ordering": ["-weight"],
                "indexes": [
                    models.Index(
                        fields=["edge_type", "last_seen"], name="fraud_graph_edge_ty_63155e_idx"
                    ),
                    models.Index(
                        fields=["source", "target"], name="fraud_graph_source__c58a57_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "target", "edge_type"), name="uq_graph_edge_pair_type"
                    )
                ],
            },
        ),
    ]
