# Generated by Django 5.2.16 on 2026-08-08 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_booking_security_deposit_amount_and_more"),
        ("payments", "0002_invoice_paymentauditlog_paymentschedule"),
        ("rooms", "0002_room_tier_room_tier_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotion_payments",
                to="rooms.room",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="bookings.booking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("booking_deposit", "Booking Deposit"),
                    ("monthly_rent", "Monthly Rent"),
                    ("security_deposit", "Security Deposit"),
                    ("listing_feature", "Listing Feature"),
                    ("listing_premium", "Listing Premium"),
                ],
                max_length=20,
            ),
        ),
    ]
