# Generated by Django 5.2.17 on 2026-08-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_payment_room_alter_payment_booking_and_more"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("booking_deposit", "Booking Deposit"),
                    ("monthly_rent", "Monthly Rent"),
                    ("security_deposit", "Security Deposit"),
                    ("listing_feature", "Listing Feature"),
                    ("listing_premium", "Listing Premium"),
                    ("subscription", "Subscription"),
                ],
                max_length=20,
            ),
        ),
    ]
