# Generated by Django 5.2.17 on 2026-08-20 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("broker", "Broker"),
                            ("corporate", "Corporate"),
                            ("marketplace", "Marketplace"),
                            ("insurance", "Insurance"),
                            ("credit", "Credit"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["scope"],
            },
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("broker_booking", "Broker Booking"),
                            ("corporate_booking", "Corporate Booking"),
                            ("marketplace_order", "Marketplace Order"),
                            ("insurance_policy", "Insurance Policy"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("source_type", models.CharField(blank=True, max_length=64)),
                ("source_id", models.CharField(blank=True, max_length=128)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"], name="monetizatio_recipie_a082bb_idx"
                    ),
                    models.Index(
                        fields=["source_type", "source_id"], name="monetizatio_source__13505b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("bank", "Bank Transfer"),
                            ("manual", "Manual"),
                        ],
                        max_length=10,
                    ),
                ),
                ("account_details", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("reason", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"], name="monetizatio_recipie_10ef82_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RevenueLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("subscription_payment", "Subscription Payment"),
                            ("subscription_renewal", "Subscription Renewal"),
                            ("listing_promotion", "Listing Promotion"),
                            ("addon_sale", "Addon Sale"),
                            ("insurance_policy", "Insurance Policy"),
                            ("corporate_invoice", "Corporate Invoice"),
                            ("commission_broker", "Broker Commission"),
                            ("commission_corporate", "Corporate Commission"),
                            ("payout", "Payout"),
                            ("refund", "Refund"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("listing", "Listing"),
                            ("broker", "Broker"),
                            ("corporate", "Corporate"),
                            ("marketplace", "Marketplace"),
                            ("insurance", "Insurance"),
                            ("credit", "Credit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "platform_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("partner_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="BDT", max_length=8)),
                ("source_type", models.CharField(blank=True, max_length=64)),
                ("source_id", models.CharField(blank=True, max_length=128)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=128, null=True, unique=True),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scope", "created_at"], name="monetizatio_scope_04cc1f_idx"
                    )
                ],
            },
        ),
    ]
