# Generated by Django 5.2.17 on 2026-09-01 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("chat", "0004_message_edited_at_message_is_deleted_and_more"),
        ("rooms", "0008_add_photo_geo_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Negotiation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "negotiation_key",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("active", "Active"),
                            ("offer_pending", "Offer pending"),
                            ("counter_offer_pending", "Counter offer pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="initiated",
                        max_length=24,
                    ),
                ),
                ("tenant_constraints", models.JSONField(blank=True, default=dict)),
                ("landlord_constraints", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="negotiations",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiations_as_landlord",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "landlord_conversation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="negotiation_as_landlord",
                        to="agents.agentconversation",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiations",
                        to="rooms.room",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiations_as_tenant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant_conversation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="negotiation_as_tenant",
                        to="agents.agentconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Negotiation",
                "verbose_name_plural": "Negotiations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="NegotiationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=32)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "negotiation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="negotiation_agent.negotiation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Negotiation event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NegotiationOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "offer_key",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("offer", "Offer"), ("counter", "Counter offer")],
                        default="offer",
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                ("message", models.TextField(blank=True, default="")),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="negotiation_offer",
                        to="chat.message",
                    ),
                ),
                (
                    "negotiation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="negotiation_agent.negotiation",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="negotiation_offer",
                        to="agents.agentproposal",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiation_offers_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Negotiation offer",
                "verbose_name_plural": "Negotiation offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="negotiation",
            index=models.Index(
                fields=["status", "expires_at"], name="negotiation_status_878569_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="negotiation",
            constraint=models.UniqueConstraint(
                fields=("room", "tenant", "landlord"), name="uniq_negotiation_per_room_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="negotiationevent",
            index=models.Index(
                fields=["negotiation", "-created_at"], name="negotiation_negotia_45e9c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="negotiationoffer",
            index=models.Index(
                fields=["negotiation", "status", "-created_at"],
                name="negotiation_negotia_e59776_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="negotiationoffer",
            index=models.Index(
                fields=["status", "expires_at"], name="negotiation_status_e42b4e_idx"
            ),
        ),
    ]
