# Generated by Django 5.2.17 on 2026-08-31 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0008_add_photo_geo_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("week_key", models.CharField(db_index=True, max_length=16)),
                ("eligible", models.BooleanField(default=False)),
                ("eligibility_blocks", models.JSONField(blank=True, default=list)),
                ("quality_score", models.IntegerField(blank=True, null=True)),
                ("quality_level", models.CharField(blank=True, default="", max_length=16)),
                ("property_score", models.IntegerField(blank=True, null=True)),
                ("property_confidence", models.CharField(blank=True, default="", max_length=16)),
                ("price_direction", models.CharField(blank=True, default="hold", max_length=8)),
                (
                    "suggested_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("photo_count", models.IntegerField(default=0)),
                ("stale_days", models.IntegerField(default=0)),
                (
                    "grounding_key",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autopilot_analyses",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing analysis",
                "verbose_name_plural": "Listing analyses",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room", "week_key"), name="uniq_autopilot_analysis_room_week"
                    )
                ],
            },
        ),
    ]
