"""AI Intelligence Layer — Phase 18.1 + 18.2 + 18.3 + 18.4 URL configuration."""

from django.urls import path

from . import views

app_name = "ai_intelligence"

urlpatterns = [
    # Feature registry
    path(
        "features/",
        views.AIFeatureRegistryListView.as_view(),
        name="feature-list",
    ),
    path(
        "features/<str:feature_id>/",
        views.AIFeatureRegistryDetailView.as_view(),
        name="feature-detail",
    ),
    path(
        "features/<str:feature_id>/update/",
        views.AIFeatureRegistryUpdateView.as_view(),
        name="feature-update",
    ),
    # Prompt registry
    path(
        "prompts/",
        views.AIPromptListView.as_view(),
        name="prompt-list",
    ),
    path(
        "prompts/<str:prompt_key>/",
        views.AIPromptDetailView.as_view(),
        name="prompt-detail",
    ),
    path(
        "prompts/<str:prompt_key>/versions/",
        views.AIPromptVersionListView.as_view(),
        name="prompt-version-list",
    ),
    path(
        "prompts/<str:prompt_key>/versions/<int:version>/",
        views.AIPromptVersionDetailView.as_view(),
        name="prompt-version-detail",
    ),
    path(
        "prompts/<str:prompt_key>/versions/<int:version>/activate/",
        views.AIPromptActivateView.as_view(),
        name="prompt-version-activate",
    ),
    path(
        "prompts/<str:prompt_key>/deactivate/",
        views.AIPromptDeactivateView.as_view(),
        name="prompt-version-deactivate",
    ),
    path(
        "prompts/<str:prompt_key>/rollback/",
        views.AIPromptRollbackView.as_view(),
        name="prompt-rollback",
    ),
    path(
        "prompts/<str:prompt_key>/compare/",
        views.AIPromptCompareView.as_view(),
        name="prompt-compare",
    ),
    # Execution logs
    path(
        "logs/",
        views.AIExecutionLogListView.as_view(),
        name="log-list",
    ),
    path(
        "logs/<uuid:execution_id>/",
        views.AIExecutionLogDetailView.as_view(),
        name="log-detail",
    ),
    # Provider health
    path(
        "health/",
        views.ProviderHealthListView.as_view(),
        name="health-list",
    ),
    path(
        "health/stats/",
        views.ProviderStatsView.as_view(),
        name="health-stats",
    ),
    path(
        "health/update/",
        views.UpdateProviderHealthView.as_view(),
        name="health-update",
    ),
    # Phase 18.3 — Evaluation Framework
    # Metrics
    path(
        "eval/metrics/",
        views.EvaluationMetricListView.as_view(),
        name="eval-metric-list",
    ),
    # Datasets
    path(
        "eval/datasets/",
        views.EvaluationDatasetListView.as_view(),
        name="eval-dataset-list",
    ),
    path(
        "eval/datasets/<int:pk>/",
        views.EvaluationDatasetDetailView.as_view(),
        name="eval-dataset-detail",
    ),
    path(
        "eval/datasets/<int:dataset_id>/cases/",
        views.EvaluationCaseListView.as_view(),
        name="eval-case-list",
    ),
    # Thresholds
    path(
        "eval/thresholds/",
        views.EvaluationThresholdListView.as_view(),
        name="eval-threshold-list",
    ),
    # Evaluation runs
    path(
        "eval/runs/",
        views.EvaluationRunListView.as_view(),
        name="eval-run-list",
    ),
    path(
        "eval/runs/<int:pk>/",
        views.EvaluationRunDetailView.as_view(),
        name="eval-run-detail",
    ),
    path(
        "eval/runs/<int:run_id>/execute/",
        views.EvaluationRunExecuteView.as_view(),
        name="eval-run-execute",
    ),
    path(
        "eval/runs/<int:run_id>/cancel/",
        views.EvaluationRunCancelView.as_view(),
        name="eval-run-cancel",
    ),
    path(
        "eval/runs/<int:run_id>/results/",
        views.EvaluationCaseResultListView.as_view(),
        name="eval-case-result-list",
    ),
    # Comparisons
    path(
        "eval/compare/runs/",
        views.RunComparisonView.as_view(),
        name="eval-compare-runs",
    ),
    path(
        "eval/compare/models/",
        views.ModelComparisonView.as_view(),
        name="eval-compare-models",
    ),
    path(
        "eval/compare/prompts/",
        views.PromptComparisonView.as_view(),
        name="eval-compare-prompts",
    ),
    # Regression + baselines
    path(
        "eval/regression/check/",
        views.RegressionCheckView.as_view(),
        name="eval-regression-check",
    ),
    path(
        "eval/baselines/",
        views.BaselineListView.as_view(),
        name="eval-baseline-list",
    ),
    # Phase 18.4 — AI Intelligence Dashboard
    path(
        "dashboard/summary/",
        views.AIDashboardSummaryView.as_view(),
        name="dashboard-summary",
    ),
    path(
        "dashboard/features/",
        views.AIFeatureHealthListView.as_view(),
        name="dashboard-features",
    ),
    path(
        "dashboard/features/<str:feature_id>/",
        views.AIFeatureHealthDetailView.as_view(),
        name="dashboard-feature-detail",
    ),
    path(
        "dashboard/models/",
        views.AIModelHealthView.as_view(),
        name="dashboard-models",
    ),
    path(
        "dashboard/models/compare/",
        views.AIModelCompareView.as_view(),
        name="dashboard-models-compare",
    ),
    path(
        "dashboard/providers/",
        views.AIProviderHealthView.as_view(),
        name="dashboard-providers",
    ),
    path(
        "dashboard/cost/",
        views.AICostDashboardView.as_view(),
        name="dashboard-cost",
    ),
    path(
        "dashboard/performance/",
        views.AIPerformanceDashboardView.as_view(),
        name="dashboard-performance",
    ),
    path(
        "dashboard/errors/",
        views.AIErrorDashboardView.as_view(),
        name="dashboard-errors",
    ),
    path(
        "dashboard/quality/",
        views.AIQualityDashboardView.as_view(),
        name="dashboard-quality",
    ),
    path(
        "dashboard/drift/",
        views.AIDriftStatusView.as_view(),
        name="dashboard-drift",
    ),
    path(
        "dashboard/prompts/",
        views.AIPromptHealthView.as_view(),
        name="dashboard-prompts",
    ),
    # Phase 18.4 — AI Alerts
    path(
        "alerts/rules/",
        views.AIAlertRuleListCreateView.as_view(),
        name="alert-rule-list",
    ),
    path(
        "alerts/rules/<int:pk>/",
        views.AIAlertRuleDetailView.as_view(),
        name="alert-rule-detail",
    ),
    path(
        "alerts/",
        views.AIAlertListView.as_view(),
        name="alert-list",
    ),
    path(
        "alerts/evaluate/",
        views.AIAlertEvaluateView.as_view(),
        name="alert-evaluate",
    ),
    path(
        "alerts/<int:pk>/",
        views.AIAlertDetailView.as_view(),
        name="alert-detail",
    ),
    path(
        "alerts/<int:pk>/acknowledge/",
        views.AIAlertAcknowledgeView.as_view(),
        name="alert-acknowledge",
    ),
    path(
        "alerts/<int:pk>/resolve/",
        views.AIAlertResolveView.as_view(),
        name="alert-resolve",
    ),
    path(
        "alerts/<int:pk>/suppress/",
        views.AIAlertSuppressView.as_view(),
        name="alert-suppress",
    ),
]
