# Generated by Django 5.2.16 on 2026-08-13 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_referral_code_user_referred_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tenant_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TenantVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("needs_review", "Needs Review"),
                        ],
                        default="not_started",
                        max_length=16,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        blank=True,
                        choices=[("nid", "National ID (NID)"), ("passport", "Passport")],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="tenant_kyc/%Y/%m/")),
                ("review_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
