# Generated by Django 5.2.16 on 2026-08-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_tenant_verified_tenantverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="digest_emails_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
