# Generated by Django 5.2.16 on 2026-08-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_digest_emails_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantverification",
            name="auto_screen_detail",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenantverification",
            name="auto_screen_result",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="tenantverification",
            name="auto_screen_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
