# Generated by Django 5.2.16 on 2026-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_tenantverification_auto_screen_detail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsOtpChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=16)),
                ("code_hash", models.CharField(max_length=64)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                            ("locked", "Locked"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
