# Generated by Django 5.2.16 on 2026-08-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_smsotpchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="market_report_emails_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
