# Generated by Django 5.2.17 on 2026-08-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_user_market_report_emails_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("tenant", "Tenant"),
                    ("landlord", "Landlord"),
                    ("admin", "Admin"),
                    ("broker", "Broker"),
                ],
                default="tenant",
                max_length=10,
            ),
        ),
    ]
