# Generated by Django 5.2.17 on 2026-08-20 10:37

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycdocument",
            name="file",
            field=models.FileField(
                storage=config.storage.PrivateMediaStorage(), upload_to="kyc_documents/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="tenantverification",
            name="file",
            field=models.FileField(
                blank=True,
                storage=config.storage.PrivateMediaStorage(),
                upload_to="tenant_kyc/%Y/%m/",
            ),
        ),
    ]
