# Generated by Django 5.2.17 on 2026-08-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_kycdocument_file_alter_tenantverification_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantverification",
            name="face_match_score",
            field=models.IntegerField(
                blank=True,
                help_text="Face-match similarity score 0-100 from the provider.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenantverification",
            name="face_match_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Face-match status: empty (not started), pending, passed, failed, needs_review.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tenantverification",
            name="liveness_score",
            field=models.IntegerField(
                blank=True,
                help_text="Liveness confidence score 0-100 from the provider.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenantverification",
            name="liveness_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Liveness check status: empty (not started), pending, passed, failed, needs_review.",
                max_length=16,
            ),
        ),
    ]
