# Generated by Django 5.2.17 on 2026-08-22 06:33

import config.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_tenantverification_face_match_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivenessChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("blink", "Blink Detection"),
                            ("smile", "Smile Detection"),
                            ("turn_head", "Turn Head"),
                            ("text_challenge", "Follow Instructions"),
                        ],
                        default="blink",
                        max_length=20,
                    ),
                ),
                (
                    "selfie",
                    models.ImageField(
                        blank=True,
                        help_text="User selfie captured during liveness check (private, auto-deleted after 90 days).",
                        null=True,
                        storage=config.storage.PrivateMediaStorage(),
                        upload_to="kyc/liveness/%Y/%m/",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of the liveness provider used (e.g. 'rules', 'http').",
                        max_length=50,
                    ),
                ),
                (
                    "provider_score",
                    models.IntegerField(
                        blank=True, help_text="Provider confidence score 0-100.", null=True
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, help_text="Raw provider response for audit trail."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Challenge expires after this time (default 15 minutes).",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liveness_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="users_liven_user_id_ae560c_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="LivenessConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("liveness", "Liveness Detection"),
                            ("face_match", "Face Match Comparison"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "granted",
                    models.BooleanField(
                        default=False, help_text="True if user has granted consent."
                    ),
                ),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liveness_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-granted_at"],
                "unique_together": {("user", "consent_type")},
            },
        ),
    ]
